### ISSUE TITLE
The generated log files cannot be written to

### ISSUE THREAD

**Issue by yomiiiiiiii** [adamslab-ub/Real-Time-Outage-Management-Active-DNR-GRL#1]
Excuse me，I'm sorry to bother you, but I encountered some issues while running your program.
When running train.py, I found that the log files generated in the Tensorboard_logger directory were not being updated with training data. Have you encountered this issue during your runs as well?

**Comment by yomiiiiiiii** [comment]
> Excuse me，I'm sorry to bother you, but I encountered some issues while running your program. When running train.py, I found that the log files generated in the Tensorboard_logger directory were not being updated with training data. Have you encountered this issue during your runs as well?

**Comment by FinallyKiKi** [comment]
This problem is probably due to the program constantly repeating the reset function and not really entering the training stage. This can be found by adjusting the logging level to INFO. I have also encountered the same problem. Do you know the solution?
